### PR TITLE
human_*: Rename default -> <default>

### PR DESCRIPTION
**Pull request by DolceTriade**
default doesn't exist and it causes a warning every map load. <default>
does exist and does not cause a warning..

### CODE REVIEW

**Comment by illwieckz** [comment]
This hides the warning but we still need an opened issue are this is just hiding the issue in models.

**Comment by DolceTriade** [comment]
There is no issue in the models. The reason that these shaders don't mean anything is that we override these shaders using skins.

**Comment by illwieckz** [comment]
For a start we don't have the information just by reading the shader names in the model file what is textured by head texture and what is the surface textured with body texture.

Also it's useful to be able to open the model in other tools.

**Comment by DolceTriade** [comment]
We can make the shaders be the default human skin... rather than `<default>`.

**Comment by illwieckz** [comment]
Yes that's why I opened another issue, this PR is perfectly fine.

If I have not deleted it by mistake, I already have a branch fixing the model textures, otherwise I can redo it, it just never looked as a priority to me.

Silencing the warning this way is fine as long as we don't forget we can do more, and since https://github.com/Unvanquished/Unvanquished/issues/2000 exists we won't forget.

**Review by illwieckz — APPROVED** [review]
LGTM

**Pull request merged**
