### PR TITLE
Make jetpack sound mono

### PR DESCRIPTION
**Pull request by necessarily-equal**
Stereo sound are not dampened with distance. See https://github.com/UnvanquishedAssets/res-weapons_src.dpkdir/issues/6#issuecomment-767569140

### CODE REVIEW

**Comment by illwieckz** [comment]
Ah, nice find!

Is there a reason it went from 24-bit precision to 16-bit precision? I was surprised the size was not the half but the close to the quarter of the original sound file, and then going from stereo to mono divided the size by two, and from 24-bit to 16-bit almost divided by two again.

Is it a channel split (taking only left or right channel and dropping the other one) or a downmix from stereo (merging the two channels in one)?

**Comment by illwieckz** [comment]
For reference, on my end for this kind of use case, what I do is:

```
ffmpeg -i hi.flac -ac 1 hi_mono.flac
```

Which is supposed to to a downmix if I'm right.

Then I optimize the resulting FLAC fille using [FileOptimize](https://sourceforge.net/projects/nikkhokkho/files/FileOptimizer/) (on wine).

What is the tool used? Outside of the problem of precision destruction by going from 24-bit to 16-bit (which is bad), I'm surprised FileOptimiser can't optimize any extra byte from the file you produced (which looks very good at first glance)? I'm looking for tools to recommend, so this question is part of me evaluating tools.

```sh
$ file hi.flac hi_mono.ffmpeg.flac hi_mono.FileOptimizer.flac hi_mono.afontain.flac
hi.flac:                    FLAC audio bitstream data, 24 bit, stereo, 44.1 kHz, 176400 samples
hi_mono.ffmpeg.flac:        FLAC audio bitstream data, 24 bit, mono, 44.1 kHz, 176400 samples
hi_mono.FileOptimizer.flac: FLAC audio bitstream data, 24 bit, mono, 44.1 kHz, 176400 samples
hi_mono.afontain.flac:      FLAC audio bitstream data, 16 bit, mono, 44.1 kHz, 176400 samples

$ du -b hi.flac hi_mono.ffmpeg.flac hi_mono.FileOptimizer.flac hi_mono.afontain.flac
647545	hi.flac
352539	hi_mono.ffmpeg.flac
345004	hi_mono.FileOptimizer.flac
168580	hi_mono.afontain.flac
```

Note: while writing this, I noticed FileOptimize says on console it can't optimize your file because being too small, so it's all about going from 24-bit to 16-bit:

```
FAILURE: Compression failed (ratio 1,043, should be < 1.0).
This happens for some files for one or more of the following reasons:
 * Recompressing an existing FLAC from a higher to a lower compression setting.
 * Insufficient input data  (e.g. very short files, < 10000 frames).
 * The audio data is not compressible (e.g. a full range white noise signal).
1177/1178 Unable to compress further. (copying)
```

So this does not mean anything about the performance of the compression.

**Comment by necessarily-equal** [comment]
Hi,

for that, I used audacity and kept only one channel as they sounded 
equivalent. I don't think there is a noticeable (audible) difference 
here, but feel free to redo it properly.

**Comment by illwieckz** [comment]
I have done some research, and I now get flac files the FileOptimiser tool can't compress more, one can find my updated `drt-flacbrute` tool in my [datarepotools](https://github.com/illwieckz/datarepotools/) repository. I noticed even the 16bit flac produced by audacity can save some space with that script even if FileOptimizer files.

About 24 bit and 16 bit, [according to this page](https://www.musicologique.fr/16bits-vs-24bits-que-choisir-et-pourquoi/), the difference between 24-bit and 16-bit is inaudible, but it is useful to keep in source files since it can reduce artifacts when editing.

Another point is that we may prefer to let Urcheon convert our source files to mono (and maybe reduce to 16-bit). I'll see if we can predict which file must be stereo and which file must be mono and if it's possible, let Urcheon convert stuff instead, otherwise I'll redo the PR with an optimized 24-bit mono sound.

**Comment by ghost** [comment]
ping: is there's still a reason to not merge?

**Comment by illwieckz** [comment]
Merged by hand with commit redone.

**Pull request closed without merging**
